project:
  type: book
  output-dir: docs

book:
  title: "Bayesian Inference"
  author: "Adrien Osakwe"
  date: "04/12/2023"
  chapters:
    - index.qmd
    - Main.qmd
    - Binomial_Model.qmd
    - Conjugate_Dist.qmd
    - PosteriorSummary.qmd
    - LikelihoodConsiderations.qmd  
    - OptimalDecisionMaking.qmd   
    - PosteriorApproximation.qmd
    - BayesianModels.qmd  
    - MoreModels.qmd
    - BayesianNonParametric.qmd
    - PracticeProblems.qmd

format:
  html:
    theme: superhero
  pdf:
    documentclass: scrreport

