project:
  type: book
  output-dir: docs

book:
  title: "Bayesian Inference"
  author: "Adrien Osakwe"
  date: "01/09/2023"
  repo-url: https://github.com/aosakwe/Bayesian-Inference
  repo-actions: [edit]
  sharing: [twitter, facebook]
  sidebar:
    search: false
    style: docked
    background: secondary
    foreground: light
    border: true
  navbar:
    background: primary
    search: false
    left: 
      - text: "Home"
        file: index.qmd
      - text: 'Practice'
        file: PracticeProblems.qmd
      - text: "Reference"
        file: Main.qmd
     
      
 
    
  chapters:
    - index.qmd
    - Main.qmd
    - Binomial_Model.qmd
    - Conjugate_Dist.qmd
    - PosteriorSummary.qmd
    - LikelihoodConsiderations.qmd  
    - OptimalDecisionMaking.qmd   
    - PosteriorApproximation.qmd
    - BayesianModels.qmd  
    - MoreModels.qmd
    - BayesianNonParametric.qmd
    - PracticeProblems.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

