project:
  type: book
  output-dir: docs

book:
  title: "Bayesian Inference"
  author: "Adrien Osakwe"
  date: "01/02/2024"
  repo-url: https://github.com/aosakwe/Bayesian-Inference
  repo-actions: [edit]
  sharing: [twitter, linkedin]

  sidebar:
    logo: cover.png
    style: "docked"
    background: secondary
    foreground: light
    border: true
    alignment: left
  navbar:
    background: primary
    left: 
      - text: "Home"
        file: index.qmd
      - text: 'Practice'
        file: PracticeProblems.qmd
      - text: "Reference"
        file: Main.qmd
  page-footer:
    center: 
      - text: "Adrien Osakwe || 2024"
        url: "https://github.com/aosakwe"
    background: primary

      
 
    
  chapters:
    - index.qmd
    - Main.qmd
    - Binomial_Model.qmd
    - Conjugate_Dist.qmd
    - PosteriorSummary.qmd
    - LikelihoodConsiderations.qmd  
    - OptimalDecisionMaking.qmd   
    - PosteriorApproximation.qmd
    - BayesianModels.qmd  
    - MoreModels.qmd
    - BayesianNonParametric.qmd
    - PracticeProblems.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

